AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Full stack: DynamoDB + Lambda + API Gateway + CloudWatch + DevOps Guru

Globals:
  Function:
    Runtime: nodejs18.x
    Timeout: 10
    MemorySize: 128

Resources:

  ReceiptsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ReceiptsTable
      AttributeDefinitions:
        - AttributeName: receiptId
          AttributeType: S
      KeySchema:
        - AttributeName: receiptId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  ReceiptFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReceiptReaderFunction
      Handler: index.handler
      CodeUri: .
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /read-receipt
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: ReceiptsTable
        - CloudWatchPutMetricPolicy: {}

  LambdaInvokeSchedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(5 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ReceiptFunction.Arn
          Id: TargetFunction
      Name: LambdaEvery5Minutes

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ReceiptFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt LambdaInvokeSchedule.Arn

  DevOpsGuruMonitor:
    Type: AWS::DevOpsGuru::MonitoringConfiguration
    Properties:
      ResourceCollection:
        CloudFormation:
          StackNames:
            - !Ref AWS::StackName

Outputs:
  APIEndpoint:
    Description: "Invoke URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/read-receipt"
