name: Docker image
 
on:
  push:
 
env:
  AWS_REGION: eu-west-1
  ROLE_TO_ASSUME: arn:aws:iam::144317819575:role/odic
  ECR_REPO: first

     
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}
 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
 
    - name: Build, tag, and push image to ECR
      run: |
        IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest"
        docker build -t $IMAGE_URI ./app
        docker push $IMAGE_URI
        echo "image_uri=$IMAGE_URI" >> $GITHUB_ENV
